// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yarwbwvmfrvwseudcmza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlhcndid3ZtZnJ2d3NldWRjbXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTg5ODgsImV4cCI6MjA2OTM3NDk4OH0.7UEItkoPTtWc3VrtufKZGx5CElbJsnGZareslx9DdgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});